### ISSUE TITLE
vc.js fails to verify a MTR credential

### ISSUE THREAD

**Issue by acarnagey** [transmute-industries/verifiable-data#102]
On testing a MTR credential the library fails to expand the document on verification of the credential
```
{
      verified: false,
      error: VerificationError: Verification error(s).
          at /Users/adam/git/mute/verifiable-data/packages/linked-data-proof/src/verify.ts:33:22
          at processTicksAndRejections (internal/process/task_queues.js:93:5) {
        errors: [
          Error: The property "grade" in the input was not defined in the context.
              at strictExpansionMap (/Users/adam/git/mute/verifiable-data/packages/linked-data-proof/src/strictExpansionMap.ts:4:11)
              at _expandObject (/Users/adam/git/mute/verifiable-data/packages/ed25519-signature-2018/node_modules/jsonld/lib/expand.js:445:26)
              at Object.<anonymous>.api.expand (/Users/adam/git/mute/verifiable-data/packages/ed25519-signature-2018/node_modules/jsonld/lib/expand.js:248:9)
              at _expandObject (/Users/adam/git/mute/verifiable-data/packages/ed25519-signature-2018/node_modules/jsonld/lib/expand.js:795:35)
              at processTicksAndRejections (internal/process/task_queues.js:93:5)
              at Object.<anonymous>.api.expand (/Users/adam/git/mute/verifiable-data/packages/ed25519-signature-2018/node_modules/jsonld/lib/expand.js:248:3)
              at _expandObject (/Users/adam/git/mute/verifiable-data/packages/ed25519-signature-2018/node_modules/jsonld/lib/expand.js:795:25)
              at Object.<anonymous>.api.expand (/Users/adam/git/mute/verifiable-data/packages/ed25519-signature-2018/node_modules/jsonld/lib/expand.js:248:3)
              at Function.jsonld.expand (/Users/adam/git/mute/verifiable-data/packages/ed25519-signature-2018/node_modules/jsonld/lib/jsonld.js:325:18)
              at Function.jsonld.toRDF (/Users/adam/git/mute/verifiable-data/packages/ed25519-signature-2018/node_modules/jsonld/lib/jsonld.js:671:16)
        ]
      }
    }
```

**Comment by OR13** [comment]
@acarnagey don't forget to document the fix, link to commits / PRs and close this issue after that.

**Comment by acarnagey** [comment]
Linked the PR, the fix was to use the same defaults that Digital Bazaar uses for vc-js.  To make the defaults the same in our vc.js package compactProof and expansionMap are defaulted to false in packages/linked-data-proof/src/ProofSet.ts verify()
