### ISSUE TITLE
"type": "MISSING_PROPERTIES_IN_CONTEXT",

### ISSUE THREAD

**Issue by bishalkc** [transmute-industries/verifiable-data#132]
I am trying to create a credential and getting `MISSING_PROPERTIES_IN_CONTEXT`, I have verified json-ld and seems to be valid. Can you please suggest what I am missing?

My VC 
```

{
  "@context": [
    "https://www.w3.org/2018/credentials/v1",
    "https://w3id.org/security/suites/jws-2020/v1"
  ],
  "id": "http://example.edu/credentials/3732",
  "type": [
    "VerifiableCredential"
  ],
  "issuer": {
    "id": "did:key:z6MkokrsVo8DbGDsnMAjnoHhJotMbDZiHfvxM4j65d8prXUr"
  },
  "issuanceDate": "2010-01-01T19:23:24Z",
  "credentialSubject": {
    "id": "did:example:ebfeb1f712ebc6f1c276e12ec21"
  }
}
```

And the error 

```
(node:41427) Warning: Accessing non-existent property 'abort' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
Error: credential is not valid JSON-LD: {
  "type": "MISSING_PROPERTIES_IN_CONTEXT",
  "details": [
    "credentialSubject",
    "issuanceDate",
    "issuer"
  ]
}
    at /Users/Code/research/testvc/node_modules/@transmute/vc.js/src/checkCredential.ts:58:11
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

Thanks

**Comment by OR13** [comment]
Seems like the document loader you are using is not dereferencing `https://www.w3.org/2018/credentials/v1` correctly, here is your credential signed:

https://api.did.actor/v/eJylkVuXmjAUhf9L-qpCoqDyVO_F24y3cbSrD5AcNIqAJIA4y__egF2d9rVdKy_J2mefb-98oK80DCTcJLK-o6OUkbA0LcuyWlavhfFBIzpuaTQGBoHkji-0FKPKp7DOWSkTQJOYy1wTCZcgtFMmqkQneiH_UUGcIascUjNwcy6RDzVgyV_G9WadKGuZR1CwvEHMPe64PvR-i0orIRKIlR3jzDpDbt3N2Vny1f06bJ-vGdu03s6sO7kZ5mB3f_eiQzB_3XRG9yDidM63XoCeHk5Aoe9ItQupjHpVx-qscdsidYs09kr1CbdK3BNQVdHHM0mx-lcMC1wPXOw1MQGXmh6mpGmCulCC0aOCojgMvWLwmQsNGDEM3F7xQ-DIJIai3-cuxcJKGEJKGGONTYtgq4ELmLSsgzqSh8EM5DFk_1HBl3_orAzymsRRKIocjhAQ_wFTQerL1Tvk46M7ovyFj4f7wXK9WNnCvthk3rPN_WUoKNmo-zx33hf8xRd8d9rpto_btdpu3uhOk0Wzsx59Y6S1NO3tdJVNw7Q3uZwSr5-m3aonM8fwfUO0cb-VRbPqccnwOI5mwnbDOB1dt8dJTs1s7S0v951LOxl6PH4CeBz3GQ


See these examples: https://github.com/transmute-industries/api.did.actor/blob/main/vc-api/facade/transmute-vc-api.ts#L22

**Comment by bishalkc** [comment]
Thank, 

I had the wrong version. 

Appreciate much

**Comment by OR13** [comment]
Closing this issue, but feel free to open more!

**Comment by OR13** [comment]
@bishalkc your document loader needs to be configured to resolve `did:key:`. (or any other did you choose to support).


Here is an example:

https://github.com/transmute-industries/api.did.actor/blob/main/core/documentLoader.ts#L18


Here is another example:

https://did.key.transmute.industries/did:key:z6Mkti5rMbb4W3FkHEyWd5pyRHDEeRKJ9BUL3jamQUvsQPbX

https://github.com/transmute-industries/did-key.js/blob/main/packages/website/src/utils/resolve.js#L4

**Comment by bishalkc** [comment]
It seems to be resolving 
```
did url = did:key:z6MkkV6JLrpasKiLJxHnvAhS7PhjjDTdkD7fP6erRBxaS7Qt#z6MkkV6JLrpasKiLJxHnvAhS7PhjjDTdkD7fP6erRBxaS7Qt
```

```did document 
{
  '@context': [
    'https://www.w3.org/ns/did/v1',
    'https://w3id.org/security/suites/ed25519-2018/v1',
    'https://w3id.org/security/suites/x25519-2019/v1'
  ],
  id: 'did:key:z6MkkV6JLrpasKiLJxHnvAhS7PhjjDTdkD7fP6erRBxaS7Qt',
  verificationMethod: [
    {
      id: 'did:key:z6MkkV6JLrpasKiLJxHnvAhS7PhjjDTdkD7fP6erRBxaS7Qt#z6MkkV6JLrpasKiLJxHnvAhS7PhjjDTdkD7fP6erRBxaS7Qt',
      type: 'Ed25519VerificationKey2018',
      controller: 'did:key:z6MkkV6JLrpasKiLJxHnvAhS7PhjjDTdkD7fP6erRBxaS7Qt',
      publicKeyBase58: '72qFkca9XnDsCTT6EbjbGJ9jueBnLKsJh5jvauzZWtdW'
    },
    {
      id: 'did:key:z6MkkV6JLrpasKiLJxHnvAhS7PhjjDTdkD7fP6erRBxaS7Qt#z6LSeK48PZhXsnYQSiMmihxmmY6x3AEuBaFupmq4sgLb3LaB',
      type: 'X25519KeyAgreementKey2019',
      controller: 'did:key:z6MkkV6JLrpasKiLJxHnvAhS7PhjjDTdkD7fP6erRBxaS7Qt',
      publicKeyBase58: '3dsxsFtfnKpfMKz1C4SpSwtUC1hnUy5kwo7PPDh4KxoR'
    }
  ],
  assertionMethod: [
    'did:key:z6MkkV6JLrpasKiLJxHnvAhS7PhjjDTdkD7fP6erRBxaS7Qt#z6MkkV6JLrpasKiLJxHnvAhS7PhjjDTdkD7fP6erRBxaS7Qt'
  ],
  authentication: [
    'did:key:z6MkkV6JLrpasKiLJxHnvAhS7PhjjDTdkD7fP6erRBxaS7Qt#z6MkkV6JLrpasKiLJxHnvAhS7PhjjDTdkD7fP6erRBxaS7Qt'
  ],
  capabilityInvocation: [
    'did:key:z6MkkV6JLrpasKiLJxHnvAhS7PhjjDTdkD7fP6erRBxaS7Qt#z6MkkV6JLrpasKiLJxHnvAhS7PhjjDTdkD7fP6erRBxaS7Qt'
  ],
  capabilityDelegation: [
    'did:key:z6MkkV6JLrpasKiLJxHnvAhS7PhjjDTdkD7fP6erRBxaS7Qt#z6MkkV6JLrpasKiLJxHnvAhS7PhjjDTdkD7fP6erRBxaS7Qt'
  ],
  keyAgreement: [
    'did:key:z6MkkV6JLrpasKiLJxHnvAhS7PhjjDTdkD7fP6erRBxaS7Qt#z6LSeK48PZhXsnYQSiMmihxmmY6x3AEuBaFupmq4sgLb3LaB'
  ]
}
```

**Comment by OR13** [comment]
@bishalkc is your code published somewhere I can review?

The problem is likely in the document loader, see the samples here https://github.com/transmute-industries/verifiable-data/blob/main/packages/vc.js/src/__tests__/did-key/__fixtures__/documentLoader.ts

https://github.com/transmute-industries/verifiable-data/blob/main/packages/vc.js/src/__tests__/did-key/normal.test.ts

**Comment by bishalkc** [comment]
Thanks I will look into. 

Here is my baseline code https://github.com/bishalkc/verifiable-test

**Comment by bishalkc** [comment]
@OR13 thanks really appreciate.

Now I am getting this while trying to verify the presentation 

```
{
  "@context": [
    "https://www.w3.org/2018/credentials/v1",
    "https://w3id.org/security/suites/jws-2020/v1"
  ],
  "verifiableCredential": {
    "@context": [
      "https://www.w3.org/2018/credentials/v1",
      "https://w3id.org/security/suites/jws-2020/v1"
    ],
    "id": "http://example.edu/credentials/3732",
    "type": [
      "VerifiableCredential"
    ],
    "issuer": {
      "id": "did:key:z6MkkV6JLrpasKiLJxHnvAhS7PhjjDTdkD7fP6erRBxaS7Qt"
    },
    "issuanceDate": "2010-01-01T19:23:24Z",
    "credentialSubject": {
      "id": "did:example:ebfeb1f712ebc6f1c276e12ec21"
    },
    "proof": {
      "type": "JsonWebSignature2020",
      "created": "2022-01-06T18:02:38Z",
      "verificationMethod": "did:key:z6MkkV6JLrpasKiLJxHnvAhS7PhjjDTdkD7fP6erRBxaS7Qt#z6MkkV6JLrpasKiLJxHnvAhS7PhjjDTdkD7fP6erRBxaS7Qt",
      "proofPurpose": "assertionMethod",
      "jws": "eyJhbGciOiJFZERTQSIsImI2NCI6ZmFsc2UsImNyaXQiOlsiYjY0Il19..0yAoguuZq5_x_DWK5am1nOILibU6rp4T5cIf43liPzDxzqO2qd5inuFC5Lq3G8BOSx0tv8tDdX_wYqq1bcAoCw"
    }
  },
  "type": [
    "VerifiablePresentation"
  ],
  "holder": {
    "id": "did:example:ebfeb1f712ebc6f1c276e12ec21"
  },
  "proof": {
    "type": "JsonWebSignature2020",
    "created": "2022-01-06T18:02:38Z",
    "verificationMethod": "did:key:z6MkkV6JLrpasKiLJxHnvAhS7PhjjDTdkD7fP6erRBxaS5RT#z6MkkV6JLrpasKiLJxHnvAhS7PhjjDTdkD7fP6erRBxaS5RT",
    "proofPurpose": "authentication",
    "challenge": "123",
    "jws": "eyJhbGciOiJFZERTQSIsImI2NCI6ZmFsc2UsImNyaXQiOlsiYjY0Il19..hSFRr7fYRdcX3EG_NrkHse2XzLXZVum4L1WU8k115KKNSNX0m4_7ah6lB1C_6R5Bc3sKYVU0I-TsLETc2PMgDg"
  }
}
RangeError: Maximum call stack size exceeded
    at JSON.stringify (<anonymous>)
    at Error.stringify (/Users/bkc/Code/research/transmute/node_modules/@transmute/linked-data-proof/src/ProofSet.ts:176:21)
    at JSON.stringify (<anonymous>)
    at Error.stringify (/Users/bkc/Code/research/transmute/node_modules/@transmute/linked-data-proof/src/ProofSet.ts:176:21)
    at JSON.stringify (<anonymous>)
    at Error.stringify (/Users/bkc/Code/research/transmute/node_modules/@transmute/linked-data-proof/src/ProofSet.ts:176:21)
    at JSON.stringify (<anonymous>)
    at Error.stringify (/Users/bkc/Code/research/transmute/node_modules/@transmute/linked-data-proof/src/ProofSet.ts:176:21)
    at JSON.stringify (<anonymous>)
    at Error.value (/Users/bkc/Code/research/transmute/node_modules/@transmute/linked-data-proof/src/ProofSet.ts:176:21)
```


If i sing the vp with say issuer key its working fine but if i sign the vp with new setoff keys, I am getting above error. 

any pointers and thanks for your direction so far.

**Comment by OR13** [comment]
@BenjaminMoe I think this is related to the error serialization which is tracked in another ticket.

@bishalkc you way get something better, by console logging without `JSON.stringify`... I think we have a bug to track fixing the circular reference that is implied by this error.

**Comment by bishalkc** [comment]
I think I got this sorted, it was again documentLoader issue. Closing for now, will open again if I encounter another issue. 

Thanks for all the help.
