### ISSUE TITLE
[packages: vs.js + bbs-bls12381-signature-2020] Error: internal error in Neon module: Given messages count (8) is different from revealed messages count (9) for this proof

### ISSUE THREAD

**Issue by lukasz8888** [transmute-industries/verifiable-data#197]
Even when I temporarily comment out some code in `ProofSet.ts` causing the issue mentioned in https://github.com/transmute-industries/verifiable-data/issues/196 I get another issue.

Steps to reproduce:

```
  const key = await Bls12381G2KeyPair.generate({
    secureRandom: () => {
      return Buffer.from('4e61bc1918ea6a47ae3307331be7798196a1a8e7cfe4b6e8f7c9a5f36017d929', 'hex');
    }
  });

  const exportedKey = await key.export({ type: 'Bls12381G2Key2020' });

  const getDidDocument = (iri) => {
    return {
      documentUrl: iri,
      document: {
        '@context': ['https://www.w3.org/ns/did/v1', 'https://w3id.org/security/suites/bls12381-2020/v1'],
        id: key.controller,
        assertionMethod: [
          {
            id: exportedKey.id,
            type: exportedKey.type,
            controller: exportedKey.controller,
            publicKeyBase58: exportedKey.publicKeyBase58
          }
        ]
      }
    };
  };

  const result = await verifiable.credential.create({
    credential: {
      '@context': [
        'https://www.w3.org/2018/credentials/v1',
        'https://w3id.org/security/suites/bls12381-2020/v1',
        {
          alsoKnownAs: 'https://www.w3.org/ns/activitystreams#alsoKnownAs'
        }
      ],
      id: 'http://example.edu/credentials/3732',
      type: ['VerifiableCredential'],
      issuer: {
        id: key.controller
      },
      issuanceDate: '2010-01-01T19:23:24Z',
      credentialSubject: {
        alsoKnownAs: 'did:example:ebfeb1f712ebc6f1c276e12ec21'
      }
    },
    format: ['vc'],
    documentLoader: mockDocumentLoader,
    suite: new BbsBlsSignature2020({
      key
    })
  });

  const derivedResult = await verifiable.credential.derive({
    credential: result.items[0],
    frame: {
      '@context': ['https://www.w3.org/2018/credentials/v1', 'https://w3id.org/security/suites/bls12381-2020/v1'],
      type: ['VerifiableCredential'],
      credentialSubject: {
        alsoKnownAs: { id: {} }
      }
    },
    format: ['vc'],
    documentLoader: (iri) => {
      if (iri.startsWith(key.controller)) {
        return getDidDocument(iri);
      }
      return mockDocumentLoader(iri);
    },
    suite: new BbsBlsSignatureProof2020()
  });

  const result3 = await verifiable.credential.verify({
    credential: derivedResult.items[0],
    format: ['vc'],
    documentLoader: (iri) => {
      if (iri.startsWith(key.controller)) {
        return getDidDocument(iri);
      }
      return mockDocumentLoader(iri);
    },
    suite: [new BbsBlsSignatureProof2020()]
  });
```

After running this code above this is what `result3` is:

```
{
  verified: false,
  error: VerificationError: Verification error(s).
      at /test-project/node_modules/@transmute/linked-data-proof/dist/linked-data-proof.cjs.development.js:912:26
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at _testBls (/test-project/transmute.js:322:19)
      at /test-project/transmute.js:144:3 {
    errors: [
      Error: internal error in Neon module: Given messages count (8) is different from revealed messages count (9) for this proof
          at /test-project/node_modules/@mattrglobal/node-bbs-signatures/src/bbsSignature.ts:211:24
          at step (/test-project/node_modules/@mattrglobal/node-bbs-signatures/lib/bbsSignature.js:45:23)
          at Object.next (/test-project/node_modules/@mattrglobal/node-bbs-signatures/lib/bbsSignature.js:26:53)
          at /test-project/node_modules/@mattrglobal/node-bbs-signatures/lib/bbsSignature.js:20:71
          at new Promise (<anonymous>)
          at __awaiter (/test-project/node_modules/@mattrglobal/node-bbs-signatures/lib/bbsSignature.js:16:12)
          at Object.blsVerifyProof (/test-project/node_modules/@mattrglobal/node-bbs-signatures/src/bbsSignature.ts:207:68)
          at BbsBlsSignatureProof2020._callee8$ (/test-project/node_modules/@transmute/bbs-bls12381-signature-2020/src/BbsBlsSignatureProof2020.ts:334:30)
          at tryCatch (/test-project/node_modules/@transmute/bbs-bls12381-signature-2020/node_modules/regenerator-runtime/runtime.js:63:40)
          at Generator.invoke [as _invoke] (/test-project/node_modules/@transmute/bbs-bls12381-signature-2020/node_modules/regenerator-runtime/runtime.js:293:22)
    ]
  }
}
```

I tried multiple times with different credentials and frames to extract a different set of fields.

I always end it with the same exception:
`Error: internal error in Neon module: Given messages count (n) is different from revealed messages count (n+1) for this proof` where `n` is an integer.

**Comment by OR13** [comment]
Thanks for reporting this, we are not supporting this suite moving forward, we are waiting for https://github.com/w3c/vc-di-bbs

to publish a new version
